name: tracker_ui
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.11.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.4
  splash_screen_view: ^3.0.0
  local_auth: ^1.1.9
  http:
  provider:
  rxdart:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  assets:
    - assets/gifs/

  fonts:
    - family: CourierPrimeRegular
      fonts:
        - asset: assets/fonts/CourierPrime/CourierPrime-Regular.ttf

    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-VariableFont_wght.ttf


  uses-material-design: true
