name: tracker_ui
description: A E_main.dart Flutter project.

#  ATBB2KfPTtxR8WHcyV6pH8VygsWb66A8CD01

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.4
  splashscreen: ^1.3.5
  splash_screen_view: any
  animated_text_kit: ^4.2.1
  local_auth: ^1.1.9
  http: any
  provider: any
  rxdart: any
  flutter_session: ^0.1.1
  fluttertoast: ^8.0.9
  shared_preferences: any
  rounded_modal: ^1.0.1
  progress_dialog_null_safe: ^1.0.4
  pinput: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter_icons:
  android: true
  ios: true
  image_path: "assets/img/logo.PNG"

flutter:
  assets:
    - assets/gifs/
    - assets/img/

  fonts:
    - family: CourierPrimeRegular
      fonts:
        - asset: assets/fonts/CourierPrime/CourierPrime-Regular.ttf

    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-VariableFont_wght.ttf


  uses-material-design: true
